config/routes.rb
Rails.application.routes.draw do

  root "items#index"

  devise_for :users, controllers: {
    confirmations: 'users/confirmations',
    passwords:     'users/passwords',
    registrations: 'users/registrations',
    sessions:      'users/sessions',
    omniauth_callbacks:  "users/omniauth_callbacks"
  }

  devise_scope :user do
    ## ↓登録方法の選択ページ
    get "users/select_registration", to: 'users/registrations#select', as: :select_registration
    ## ↓電話番号認証ページ
    get "users/confirm_phone", to: 'users/registrations#confirm_phone', as: :confirm_phone
    ## ↓電話番号認証送信したとき
    post "users/pre_phone", to: 'users/registrations#pre_phone', as: :pre_phone
    ## ↓addressの登録ページ
    get "users/regist_address", to: 'users/registrations#new_address', as: :new_regist_address
    ## ↓addressのcreate
    post "users/regist_address", to: 'users/registrations#create_address', as: :regist_address
    ## ↓cardの登録ページ
    get "users/regist_payment", to: 'users/registrations#new_payment', as: :new_regist_payment
    ## ↓登録完了ページ
    get "users/regist_completed", to: 'users/registrations#completed', as: :regist_completed
  end
  
  resources :items do
    resource :purchases, only: %i(new create)
    member do
      get "purchase_confirmation"
      post "purchase"
    end
  end

  resources :categories, only: %i(index show)

  resources :item_searches, only: %i(index)

  resources :users, only: %i(show)

  resource :cards, only: %i(new create show update destroy)

  namespace :api do
    resources :items, only: [:create, :update], defaults: { format: 'json' }
    resources :categories, only: %i(index), defauluts: { format: 'json'}
  end
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: %i[google_oauth2]
  
  has_one :address, dependent: :destroy
  has_one :card, dependent: :destroy
  has_one :sns_credential, dependent: :destroy
  has_many :items, foreign_key: "user_id"
  accepts_nested_attributes_for :address

  validates :email, format:{ with: /[a-zA-Z0-9.!#$%&_~-]+@[a-zA-Z0-9-_]+\.[a-zA-Z0-9.-]+/, message: '不正な値です。'}
  validates :nickname, :birthday, presence: true
  validates :first_name, presence: true, format: { with: /\A[ぁ-んァ-ン一-龥]/, message: 'は全角で入力して下さい。'}
  validates :last_name, presence: true, format: { with: /\A[ぁ-んァ-ン一-龥]/, message: 'は全角で入力して下さい。'}
  validates :first_name_reading, presence: true, format: { with: /\A[ァ-ヶー－]+\z/, message: 'は全角（カタカナ）で入力して下さい。'}
  validates :last_name_reading, presence: true, format: { with: /\A[ァ-ヶー－]+\z/, message: 'は全角（カタカナ）で入力して下さい。'}

  private
  def self.from_omniauth(auth_data)
    email = auth_data.info.email
    nickname = auth_data.info.name
    uid = auth_data.uid
    provider = auth_data.provider

    sns_credential = SnsCredential.where(uid: uid, provider: provider).first_or_initialize

    ## sns_credentialに紐付いたuserがいるかどうか
    if sns_credential.user.present?
      ## sns_credential.userが居るならB（SNS認証で登録した）が確定するのでここで終了
      return {user: sns_credential.user, sns_credential: sns_credential}
    else
      ## sns_credentialに紐付いたuserがいない
      ## googleから送られてきたemailでuserがヒットしたらD（メールで登録した）
      ## userがヒットしなかったらA（ユーザー登録したことがない）
      user = User.where(email: email).first_or_initialize
    end

    if user.persisted?
      ## ここにきた=D（メールで登録した）
      sns_credential.user_id = user.id
      sns_credential.save
    else
      ## ここにきた＝userもsns_credentialもヒットしなかった=A（ユーザー登録したことがない）
      user.nickname = nickname
    end

    return {user: user, sns_credential: sns_credential}
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def google_oauth2
    callback_for(:google)
  end

  def callback_for(provider)
    session["devise.sns_auth"] = User.from_omniauth(request.env["omniauth.auth"])

    if session["devise.sns_auth"][:user].persisted?
      sign_in_and_redirect session["devise.sns_auth"][:user], event: :authentication
    else
      redirect_to new_user_registration_path
    end
  end

  def failure
    redirect_to root_path, alert: "エラーが発生しました" and return
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  def select
    session.delete(:"devise.sns_auth")
    @auth_text = "で登録する"
  end

  def new
    @progress = 1

    @user = User.new(session["devise.sns_auth"]["user"]) if session["devise.sns_auth"]

    super if !session["devise.sns_auth"]
  end

  def create
    if session["devise.sns_auth"]
      pass = Devise.friendly_token[8,12]
      params[:user][:password] = pass
      params[:user][:password_confirmation] = pass
      sns = SnsCredential.new(session["devise.sns_auth"]["sns"])
    end

    build_resource(sign_up_params)
    resource.build_sns_credential(session["devise.sns_auth"]["sns_credential"]) if session["devise.sns_auth"]
    unless resource.valid?
      @progress = 1
      flash.now[:alert] = ""
      resource.errors.full_messages.each do |m|
        flash.now[:alert] << m
      end
      render :new and return
    end
    session["devise.regist_data"] = {user: @user.attributes}
    session["devise.regist_data"][:user][:password] = params[:user][:password]
    redirect_to confirm_phone_path
  end

  def confirm_phone ## userのcreateに成功したらここに来る
    @progress = 2
  end

  def pre_phone
    redirect_to new_regist_address_path
  end

  def new_address ## 電話番号認証ページのボタンを押したらここに来る
    redirect_to new_regist_payment_path if session["devise.regist_data"][:address] || current_user&.address
    @progress = 3
    @address = Address.new
  end

  def create_address
    @address = Address.new(address_params)
    if @address.valid?
      redirect_to regist_completed_path and return
    else
      @progress = 3
      flash.now[:alert] = ""
      @address.errors.full_messages.each do |m|
        flash.now[:alert] << m
      end
      render :new_address and return
    end
  end

  def completed
    redirect_to root_path, alert: "エラーが発生しました" unless session["devise.regist_data"]
    @progress = 5
    @user = build_resource(session["devise.regist_data"]["user"])
    @user.build_sns_credential(session["devise.sns_auth"]["sns_credential"]) if session["devise.sns_auth"] ## sessionがあるとき＝sns認証でここまできたとき
    @user.build_address(session["devise.regist_data"]["address"])
    if @user.save
      sign_up(resource_name, resource)
    else
      redirect_to root_path, alert: @user.errors.full_messages
    end
  end

  private

  def address_params
    params.require(:address).permit(:postal_code, :prefecture, :city, :house_number, :building_name, :phone_number)
  end

  def signed_up?
    redirect_to root_path, alert: "ログインしています。" if user_signed_in?
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
  end
end

app/views/users/_side_bar.html.haml
.mypage-side-bar
  .mypage-side-bar-lists
    = render partial: 'users/side_bar_list', locals: {text: "マイページ", path: user_path(current_user), method: ""}
    = render partial: 'users/side_bar_list', locals: {text: "お知らせ", path: "", method: ""}
    = render partial: 'users/side_bar_list', locals: {text: "いいね！一覧", path: "", method: ""}
    = render partial: 'users/side_bar_list', locals: {text: "出品する", path: new_item_path, method: ""}
    = render partial: 'users/side_bar_list', locals: {text: "出品した商品---出品中", path: "", method: ""}
    = render partial: 'users/side_bar_list', locals: {text: "出品した商品---取引中", path: "", method: ""}
    = render partial: 'users/side_bar_list', locals: {text: "出品した商品---売却済", path: "", method: ""}
    = render partial: 'users/side_bar_list', locals: {text: "購入した商品---取引中", path: "", method: ""}
    = render partial: 'users/side_bar_list', locals: {text: "購入した商品---過去の取引", path: "", method: ""}
    = render partial: 'users/side_bar_list', locals: {text: "ニュース一覧", path: "", method: ""}
    = render partial: 'users/side_bar_list', locals: {text: "評価一覧", path: "", method: ""}
    = render partial: 'users/side_bar_list', locals: {text: "ガイド", path: "", method: ""}
    = render partial: 'users/side_bar_list', locals: {text: "お問い合わせ", path: "", method: ""}
  .mypage-side-bar-lists
    .mypage-side-bar-lists__top
      売上・ポイント
    = render partial: 'users/side_bar_list', locals: {text: "売上・振込申請", path: "", method: ""}
    = render partial: 'users/side_bar_list', locals: {text: "ポイント", path: "", method: ""}
  .mypage-side-bar-lists
    .mypage-side-bar-lists__top
      設定
    = render partial: 'users/side_bar_list', locals: {text: "プロフィール", path: "", method: ""}
    = render partial: 'users/side_bar_list', locals: {text: "住所変更", path: "", method: ""}
    = render partial: 'users/side_bar_list', locals: {text: "支払い方法", path: cards_path, method: ""}
    = render partial: 'users/side_bar_list', locals: {text: "メール/パスワード", path: "", method: ""}
    = render partial: 'users/side_bar_list', locals: {text: "本人情報", path: "", method: ""}
    = render partial: 'users/side_bar_list', locals: {text: "電話番号の確認", path: "", method: ""}
    = render partial: 'users/side_bar_list', locals: {text: "ログアウト", path: destroy_user_session_path, method: "delete"}

app/views/users/_side_bar_list.html.haml
= link_to path, method: "#{method}" do
  .mypage-side-bar-lists__list
    .mypage-side-bar-lists__list--left
      = text
    .mypage-side-bar-lists__list--right
      = icon "fas", "chevron-right"

app/views/users/show.html.haml
- breadcrumb :user_show, current_user
= render 'layouts/breadcrumbs'
.mypage.horizontal-padding-15
  = render 'users/side_bar'
  .mypage-main
    .mypage-block
      .mypage-block-header-user
        .mypage-block-header-user__name
          = current_user.nickname
        .mypage-block-header-user__rate
          = "評価：５ 出品数 #{current_user.items.length}"
      .mypage-block-tabs
        .mypage-block-tabs__tab.active-tab
          お知らせ
        .mypage-block-tabs__tab
          やることリスト
      .mypage-block-data-list
        .text
          現在、お知らせはありません。
    .mypage-block
      .mypage-block-header
        出品した商品
      .mypage-block-tabs
        .mypage-block-tabs__tab.active-tab
          取引中
        .mypage-block-tabs__tab
          過去の取引
      .mypage-block-data-list
        .text
          出品中の商品がありません。