config/routes.rb
Rails.application.routes.draw do

  root "items#index"

  devise_for :users, controllers: {
    confirmations: 'users/confirmations',
    passwords:     'users/passwords',
    registrations: 'users/registrations',
    sessions:      'users/sessions',
    omniauth_callbacks:  "users/omniauth_callbacks"
  }

  devise_scope :user do
    ## ↓登録方法の選択ページ
    get "users/select_registration", to: 'users/registrations#select', as: :select_registration
    ## ↓電話番号認証ページ
    get "users/confirm_phone", to: 'users/registrations#confirm_phone', as: :confirm_phone
    ## ↓電話番号認証送信したとき
    post "users/pre_phone", to: 'users/registrations#pre_phone', as: :pre_phone
    ## ↓addressの登録ページ
    get "users/regist_address", to: 'users/registrations#new_address', as: :new_regist_address
    ## ↓addressのcreate
    post "users/regist_address", to: 'users/registrations#create_address', as: :regist_address
    ## ↓cardの登録ページ
    get "users/regist_payment", to: 'users/registrations#new_payment', as: :new_regist_payment
    ## ↓登録完了ページ
    get "users/regist_completed", to: 'users/registrations#completed', as: :regist_completed
  end
  
  resources :items do
    resource :purchases, only: %i(new create)
    member do
      get "purchase_confirmation"
      post "purchase"
    end
  end

  resources :categories, only: %i(index show)

  resources :item_searches, only: %i(index)

  resources :users, only: %i(show)

  resource :cards, only: %i(new create show update destroy)

  namespace :api do
    resources :items, only: [:create, :update], defaults: { format: 'json' }
    resources :categories, only: %i(index), defauluts: { format: 'json'}
  end
  
end

app/models/item.rb
class Item < ApplicationRecord
  enum condition:{brand_new: 0, unused: 1, inconspicuous: 2, kind_of: 3, dirt: 4, old: 5}
  enum delivery_fee_payer:{seller: 0, buyer: 1}
  enum delivery_method:{Undecided: 0, merukari: 1, yu_mail: 2, letterpack: 3, post: 4, yamato: 5, yu_pack: 6, clickpost: 7, yu_packet: 8}
  enum delivery_days:{short: 0, middle: 1, long: 2}
  enum deal:{sale: 0, sold_out: 1}

  validates :name, :price, :detail, :condition, :delivery_fee_payer, :delivery_method, :prefecture_id, :delivery_days, :deal, presence: true
  validates :price, numericality:{greater_than_or_equal_to: 50,less_than_or_equal_to: 9999999}
  validates :item_images, length: { minimum: 1, message: "is none"}

  has_many :item_images, dependent: :destroy

  belongs_to :category
  belongs_to :user
  accepts_nested_attributes_for :item_images, allow_destroy: true

  scope :search_category, -> (category_id) {includes(:item_images).where(category_id: category_id)}

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :prefecture
end

app/controllers/api/items_controller.rb
class Api::ItemsController < ApplicationController

  def create
    @item = Item.new(item_params)
    @item.save
    @error = @item.errors.full_messages if @item.errors.full_messages.present?
  end

  def update
    @item = current_user.items.find(params[:id])
    @item.update(item_params)
    @error = @item.errors.full_messages if @item.errors.full_messages.present?
  end

  private
  def item_params
    params.require(:item).permit(:name, :price, :detail, :condition, :delivery_fee_payer, :delivery_method, :prefecture_id, :delivery_days, :deal, :category_id, item_images_attributes: [:image, :id, :_destroy]).merge(user_id: current_user.id)
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :sold_item, only: [:edit, :update, :destroy]
  def index
    @items = Item.order("created_at DESC").limit(3)
  end

  def show
  end

  def new ## 出品ページ
    @item = Item.new
    @item.item_images.build  ## 新規画像用
    render template: 'items/form'
  end

  def create
    redirect_to root_path, notice: "商品の出品に成功しました。" and return if params[:completed]
    @item = Item.new(item_params)
    if @item.save
      redirect_to root_path, notice: "商品の出品に成功しました。"
    else
      @item.errors.full_messages.each do |m|
        flash.now[:alert] = m
      end
      @item = Item.new(item_params)
      render template: 'items/form'
    end
  end

  def edit
    @item.item_images.build
    render template: 'items/form'
  end

  def update
    redirect_to root_path, notice: "商品の編集に成功しました。" and return if params[:completed]
    if @item.update(item_params)
      redirect_to root_path, notice: "商品の編集に成功しました。"
    else
      @item.errors.full_messages.each do |m|
        flash.now[:alert] = m
      end
      render template: 'items/form'
    end
  end

  def destroy
    @item.destroy
    redirect_to root_path, notice: "商品を削除しました。"
  end

  private
  def item_params
    params.require(:item).permit(:name, :price, :detail, :condition, :delivery_fee_payer, :delivery_method, :prefecture_id, :delivery_days, :deal, :category_id, item_images_attributes: [:image, :id, :_destroy]).merge(user_id: current_user.id)
  end

  def set_item
    begin
      @item = Item.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      redirect_to root_path, notice: "ご指定のアイテムが見つかりません。"
    end
  end

  def sold_item
    redirect_to root_path, alert: "売り切れです" if @item.deal == "sold_out"
  end
end

app/views/items/_item.html.haml
= link_to item_path(item) do 
  .list
    .list__img
      = render partial: 'layouts/sold_out', locals: {item: item}
      = image_tag item.item_images[0].image.url
    .list__body
      %h3.name
        = item.name
      .details
        %ul
          %li
            #{item.price}円

app/views/items/form.html.haml
.block
  .block__menu
    商品の情報を入力
= form_with model: @item,  local: true, html: {id: "item_form"} do |f|
  .block.horizontal-padding-5
    .input-field
      .input-field-main
        = f.label :detail, "出品画像"
        %span.required-true
          必須
        %br
        最大5枚までアップロードできます。
        #selected-item-images
          - @item.item_images.each_with_index do |image, i|
            -if image.image.url
              .item-image{data: {index: i}}
                = image_tag image.image.url, class: "item-image__image"
                .item-image__buttons
                  .item-image__buttons--edit
                    編集
                  .item-image__buttons--delete
                    削除
          #select-image-button
            #select-image-button__text
              クリックしてファイルをアップロード
    #image-file-fields
      = f.fields_for :item_images do |image|
        = image.file_field :image, class: "new-item-image", id: "file_field_index_#{image.index}", accept: "image/*", data: {index: image.index}
        - if image.object.persisted?
          = image.check_box :_destroy, include_hidden: false
          = image.hidden_field :id, value: image.object.id
      = f.file_field :image, id: "change-item-image", name: "", accept: "image/*", data: {index: ""}
    .error-field{data:{column_name: "item_images"}}
  .block.horizontal-padding-5
    .input-field
      .input-field-main
        = f.label :name, "商品名"
        %span.required-true
          必須
        %br
        = f.text_field :name, required: true, placeholder: "商品名"
        .error-field{data:{column_name: "name"}}
    .input-field
      .input-field-main
        = f.label :detail, "商品の説明"
        %span.required-true
          必須
        %br
        = f.text_area :detail, required: true, placeholder: "6文字以上", rows: 5
        .error-field{data:{column_name: "detail"}}
  .block.horizontal-padding-5
    .input-field
      .input-field-title
        .input-field-title__text
          商品の詳細
      .input-field-main
        = f.label :parent_category_id, "カテゴリ"
        %span.required-true
          必須
        = f.collection_select :category_id, Category.roots, :id , :name, {include_blank: "---", selected: @item.category&.root_id}, required: true, class: "select-category"
        - if @item.persisted?
          = f.collection_select :category_id, @item.category.root.children, :id , :name, {include_blank: "---", selected: @item.category.parent_id}, required: true, class: "select-category"
          = f.collection_select :category_id, @item.category.siblings, :id , :name, {include_blank: "---", selected: @item.category_id}, required: true, class: "select-category"
        .error-field{data:{column_name: "category"}}
        = f.label :condition, "商品の状態"
        %span.required-true
          必須
        %br
        = f.select :condition, Item.conditions_i18n.invert, {include_blank: "---", selected:"---"}
    .input-field
      .input-field-title
        .input-field-title__text
          配送について
      .input-field-main
        = f.label :delivery_fee_payer, "配送料の負担"
        %span.required-true
          必須
        %br
        = f.select :delivery_fee_payer, Item.delivery_fee_payers_i18n.invert, {include_blank: "---", selected:"---"}
        .error-field{data:{column_name: "delivery_fee_payer"}}
        %br
        .input-field-main__delivery-method
          = f.label :delivery_method, "配送の方法"
          %span.required-true
            必須
          %br
          = f.select :delivery_method, Item.delivery_methods_i18n.invert, {include_blank: "---", selected:"---"}
          %br
          .error-field{data:{column_name: "delivery_method"}}
        = f.label :prefecture_id, "発送元の地域"
        %span.required-true
          必須
        %br
        = f.collection_select :prefecture_id, Prefecture.all, :id , :name, {include_blank: "---"}, required: true, placeholder: "発送元の地域"
        .error-field{data:{column_name: "prefecture_id"}}
        %br
        = f.label :delivery_days, "発送までの日数"
        %span.required-true
          必須
        %br
        = f.select :delivery_days, Item.delivery_days_i18n.invert, {include_blank: "---", selected:"---"}
        .error-field{data:{column_name: "delivery_days"}}
  .block.horizontal-padding-5
    .input-field
      .input-field-title
        .input-field-title__text
          価格（300〜9,999,999）
      .input-field-main
        .input-field-main-price
          .input-field-main-price__left
            = f.label :price, "価格"
            %span.required-true
              必須
          .input-field-main-price__right
            = f.text_field :price, maxlength: 7,required: true, placeholder: "価格"
            .error-field{data:{column_name: "price"}}
        %hr
        .input-field-main-price
          .input-field-main-price__left
            販売手数料（10%）
          .input-field-main-price__right
            #fee
              - if @item.price
                = "¥#{(@item.price*0.1).floor}"
              - else
                \-
        %hr
        .input-field-main-price
          .input-field-main-price__left
            販売利益
          .input-field-main-price__right
            #profit
              - if @item.price
                = "¥#{@item.price - (@item.price*0.1).floor}"
              - else
                \-
  .block.horizontal-padding-5
    .information
      .information__text
        禁止されている出品、行為を必ずご確認ください。
        %br
        またブランド品でシリアルナンバー等がある場合はご記載ください。偽ブランドの販売は犯罪であり処罰される可能性があります。
        %br
        また、出品をもちまして加盟店規約に同意したことになります。
  .block.horizontal-padding-5
    = f.submit "出品する", class:"button back-main_color font-white"
    .horizontal-padding-25
      = link_to root_path do
        .button.back-gray
          戻る

app/views/items/index.html.haml
.main
  %section.mainVisual
    .content
      %h2.content__subtitle
        <br>人生を変えるフリマアプリ
      %p.content__text
        FURIMAはだれでもかんたんに出品・購入できる
        %br
        フリマアプリです
      .content__btn
        = link_to "https://tech-camp.in/expert" do
          = image_tag 'app-store.svg',class: "img3"
        = link_to "https://tech-camp.in/expert" do
          = image_tag 'google-play.svg',class: "img3"
  %section.topIntroduction.fadein
    %h2.subtitle
      FURIMAが選ばれる3つの理由
    %ul.lists
      %li.list
        .list__pict
          %span.number
            1
          = image_tag 'pict-reason-01.jpg'
        %h3.list__text
          %span 3分
          ですぐに出品
        %p.list__description
          スマホで入力するだけで簡単に出品できる！
      %li.list
        .list__pict
          %span.number
            2
          = image_tag 'pict-reason-02.jpg'
        %h3.list__text
          %span シンプル
          で使いやすい
        %p.list__description
          めんどくさい入力は必要なく、検索も購入もスムーズ！
      %li.list.list--last
        .list__pict
          %span.number
            3
          = image_tag 'pict-reason-03.jpg'
        %h3.list__text
          手数料
          %span 業界最安
        %p.list__description
          最大3%でお得に出品&購入！
  %section.topMiddleDl
    .topMiddleDl__inner
      %h2.subtitle
        会員数日本一！
      %p.text
        FURIMAは、フリマアプリで最も人気。<br>
        出品・購入回数も業界最多です！<br>
        ほしかったあの商品に出会えるかもしれません。
      .btn
        = link_to "https://tech-camp.in/expert" do
          = image_tag 'app-store.svg',class: "img3"
        = link_to "https://tech-camp.in/expert" do
          = image_tag 'google-play.svg',class: "img3"

  %section.topKeyFeatures.fadein
    %h2.head
      FURIMAの特徴
    .items
      %section.item
        %figure.item__img
          = image_tag 'icon-01.png'
        %h3.item__subtitle
          簡単に売り買いできる
        %p.item__detail
          スマホひとつで、いつでもどこでも簡単に出品・購入が可能！
      %section.item
        %figure.item__img
          = image_tag 'icon-03.png'
        %h3.item__subtitle
          売上金は即日振込みに対応
        %p.item__detail
          午前9時までに振込を依頼いただければ、翌日に指定の口座に入金いたします!
      %section.item
        %figure.item__img
          = image_tag 'icon-04.png'
        %h3.item__subtitle
          様々な支払いに対応
        %p.item__detail
          お支払いは、クレジットカードだけでなく、ポイントや売上金など多彩な方法があります。
  %section.pickupContainer
    %h2.head
      ピックアップカテゴリー
    .productBox
      .productHead
        %h3.title
          新規投稿商品
      .productLists
        = render @items
  %section.pickupContainer.last
    %h2.head
      ピックアップブランド
    .productBox
      .productHead
        %h3.title
          hogehoge
      .productLists
        .list
          .list__img
          .list__body
            %h3.name
              テスト
            .details
              %ul
                %li
                  2000円
                %li
                  ☆１
              %p
                (税込)
        .list
          .list__img
          .list__body
            %h3.name
              テスト
            .details
              %ul
                %li
                  2000円
                %li
                  ☆１
              %p
                (税込)

        .list
          .list__img
          .list__body
            %h3.name
              テスト
            .details
              %ul
                %li
                  2000円
                %li
                  ☆１
              %p
                (税込)
%aside.Banner
  .inner
    %h2.inner__title
      だれでもかんたん、人生を変えるフリマアプリ
    %p.inner__text
      今すぐ無料ダウンロード！
    .inner__icon
      = link_to "https://tech-camp.in/expert" do
        = image_tag 'app-store.svg',class: "img3"
      = link_to "https://tech-camp.in/expert" do
        = image_tag 'google-play.svg',class: "img3"

app/views/items/purchase_confirmation.html.haml
.block.horizontal-padding-25
  .block__menu
    購入内容の確認
.block.horizontal-padding-25
  .block__main
    .item-purchase-confirmation
      .item-purchase-confirmation__image-and-name
        = image_tag @item.item_images[0].image.url
      .item-purchase-confirmation__image-and-name--name
        = @item.name
      .item-purchase-confirmation__price
        .item-purchase-confirmation__price--yen
          ¥
          = @item.price
    #amount
      #amount__left
        支払金額
      #amount__right
        ¥
        = @item.price
    = link_to purchase_item_path(@item), method: :post do
      .button.back-main_color
        購入する
.block.horizontal-padding-25
  .block__menu-left
    配送先
  .block__main
    〒#{@address.postal_code}
    %br
    #{@address.city} #{@address.house_number}
    %br
    #{@address.user.first_name} #{@address.user.last_name}

.block.horizontal-padding-25
  .block__menu-left
    支払い方法
  .block__main
    #card-data
      - if @card
        = @card[:last4]
        %br
        = @card[:exp_month]
        \/
        = @card[:exp_year]
        %br
        = @card[:brand]
      - else
        \/

app/views/items/show.html.haml
- breadcrumb :item_show, @item
= render "layouts/breadcrumbs"
.block.horizontal-padding-25
  .block__menu
    = @item.name
  .item-show
    .item-show__images-data
      .item-images
        .item-images__main
          = render partial: 'layouts/sold_out', locals:{item: @item}
          = image_tag @item.item_images[0].image.url
        .item-images__mini-images
          -# = @item.item_images.each do |item_image|
          -# ミスってこう記述すると、情報が全部でちゃう。
          - @item.item_images.each do |item_image|
            = image_tag item_image.image.url
      %table.item-data
        %tr.item-data__row
          %th.item-data__row--title
            出品者
          %td.item-data__row--value
            = @item.user.nickname
        %tr.item-data__row
          %th.item-data__row--title
            カテゴリ
          %td.item-data__row--value
            = link_to @item.category.root.name
            %br
            = link_to ">#{@item.category.parent.name}"
            %br
            = link_to ">#{@item.category.name}"
        %tr.item-data__row
          %th.item-data__row--title
            商品の状態
          %td.item-data__row--value
            = @item.condition_i18n
        %tr.item-data__row
          %th.item-data__row--title
            配送料の負担
          %td.item-data__row--value
            = @item.delivery_fee_payer_i18n
        %tr.item-data__row
          %th.item-data__row--title
            配送の方法
          %td.item-data__row--value
            = @item.delivery_method_i18n
        %tr.item-data__row
          %th.item-data__row--title
            配送元地域
          %td.item-data__row--value
            = @item.prefecture.name
        %tr.item-data__row
          %th.item-data__row--title
            発送日の目安
          %td.item-data__row--value
            = @item.delivery_days_i18n
    .item-show__detail
      = simple_format @item.detail

    .item-show__price
      .item-show__price--left
        = "¥#{@item.price.to_s(:delimited)}"
      .item-show__price--middle
        （税込）
      .item-show__price--right
        = @item.delivery_fee_payer_i18n
    = link_to new_item_purchases_path(@item) do
      .button.back-main_color
        購入画面に進む
    - if user_signed_in? && @item.user_id == current_user.id
      = link_to edit_item_path(@item) do
        .button.back-gray
          商品を編集する
      = link_to item_path(@item), method: :delete do
        .button.back-gray
          商品を削除する