config/routes.rb
Rails.application.routes.draw do

  root "items#index"

  devise_for :users, controllers: {
    confirmations: 'users/confirmations',
    passwords:     'users/passwords',
    registrations: 'users/registrations',
    sessions:      'users/sessions',
    omniauth_callbacks:  "users/omniauth_callbacks"
  }

  devise_scope :user do
    ## ↓登録方法の選択ページ
    get "users/select_registration", to: 'users/registrations#select', as: :select_registration
    ## ↓電話番号認証ページ
    get "users/confirm_phone", to: 'users/registrations#confirm_phone', as: :confirm_phone
    ## ↓電話番号認証送信したとき
    post "users/pre_phone", to: 'users/registrations#pre_phone', as: :pre_phone
    ## ↓addressの登録ページ
    get "users/regist_address", to: 'users/registrations#new_address', as: :new_regist_address
    ## ↓addressのcreate
    post "users/regist_address", to: 'users/registrations#create_address', as: :regist_address
    ## ↓cardの登録ページ
    get "users/regist_payment", to: 'users/registrations#new_payment', as: :new_regist_payment
    ## ↓登録完了ページ
    get "users/regist_completed", to: 'users/registrations#completed', as: :regist_completed
  end
  
  resources :items do
    resource :purchases, only: %i(new create)
    member do
      get "purchase_confirmation"
      post "purchase"
    end
  end

  resources :categories, only: %i(index show)

  resources :item_searches, only: %i(index)

  resources :users, only: %i(show)

  resource :cards, only: %i(new create show update destroy)

  namespace :api do
    resources :items, only: [:create, :update], defaults: { format: 'json' }
    resources :categories, only: %i(index), defauluts: { format: 'json'}
  end
  
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :items
  has_ancestry
end

app/controllers/api/categories_controller.rb
class Api::CategoriesController < ApplicationController

  def index
    category = Category.find(params[:category_id])
    @categories = category.children
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
  end

  def show
    @category = Category.find(params[:id])
    @items = Item.search_category(@category.subtree_ids).order("created_at DESC")
  end

end

app/views/categories/index.html.haml
- breadcrumb :category_index
= render 'layouts/breadcrumbs'
.parent-categories.horizontal-padding-20
  .parent-categories__title
    カテゴリー一覧
  - Category.roots.each do |category|
    %span.parent-categories__category
      = link_to category_path(category) do
        = category.name
- Category.roots.each do |parent_category|
  .categories.horizontal-padding-20
    .parent-category
      = parent_category.name
    .parent-category-all
      = link_to category_path(parent_category) do
        すべて
    - parent_category.children.each do |child_category|
      .child-category
        %h4
          = child_category.name
        .child-category__grand-child-categories
          = link_to category_path(child_category), class: "child-category__grand-child-categories--category" do
            すべて
          - child_category.children.each do |grandchild_category|
            = link_to grandchild_category.name, category_path(grandchild_category), class: "child-category__grand-child-categories--category"

app/views/categories/show.html.haml
- breadcrumb :category_show, @category
= render "layouts/breadcrumbs"
.items-wrapper.horizontal-padding-20
  .items-wrapper__title
    = "#{@category.name}の商品一覧"
  .productLists
    = render @items
  -# = paginate(@items)