config/routes.rb
Rails.application.routes.draw do

  root "items#index"

  devise_for :users, controllers: {
    confirmations: 'users/confirmations',
    passwords:     'users/passwords',
    registrations: 'users/registrations',
    sessions:      'users/sessions',
    omniauth_callbacks:  "users/omniauth_callbacks"
  }

  devise_scope :user do
    ## ↓登録方法の選択ページ
    get "users/select_registration", to: 'users/registrations#select', as: :select_registration
    ## ↓電話番号認証ページ
    get "users/confirm_phone", to: 'users/registrations#confirm_phone', as: :confirm_phone
    ## ↓電話番号認証送信したとき
    post "users/pre_phone", to: 'users/registrations#pre_phone', as: :pre_phone
    ## ↓addressの登録ページ
    get "users/regist_address", to: 'users/registrations#new_address', as: :new_regist_address
    ## ↓addressのcreate
    post "users/regist_address", to: 'users/registrations#create_address', as: :regist_address
    ## ↓cardの登録ページ
    get "users/regist_payment", to: 'users/registrations#new_payment', as: :new_regist_payment
    ## ↓登録完了ページ
    get "users/regist_completed", to: 'users/registrations#completed', as: :regist_completed
  end
  
  resources :items do
    resource :purchases, only: %i(new create)
    member do
      get "purchase_confirmation"
      post "purchase"
    end
  end

  resources :categories, only: %i(index show)

  resources :item_searches, only: %i(index)

  resources :users, only: %i(show)

  resource :cards, only: %i(new create show update destroy)

  namespace :api do
    resources :items, only: [:create, :update], defaults: { format: 'json' }
    resources :categories, only: %i(index), defauluts: { format: 'json'}
  end
  
end

app/views/layouts/_breadcrumbs.html.haml
.breadcrumbs-wrapper.horizontal-padding-15
  = breadcrumbs pretext: "", separator: " &rsaquo; "

app/views/layouts/_flash.html.haml
- flash.each do |key, value|
  = content_tag(:div, value, class: "flash flash__#{key}")

app/views/layouts/_footer.html.haml
.footer
  %ul.contents
    %li.content
      %h2.content__head
        FURIMAについて
      %ul
        %li
          会社概要（運営会社）
        %li
          プライバシーポリシー
        %li
          FURIMA利用規約
        %li
          ポイントに関する規約
    %li.content
      %h2.content__head
        FURIMAを見る
      %ul
        %li
          カテゴリー一覧
        %li
          ブランド一覧
    %li.content
      %h2.content__head
        ヘルプ＆ガイド
      %ul
        %li
          FURIMAガイド
        %li
          FURIMAロゴ利用ガイドライン
        %li
          お知らせ
  .footer__logo
    = image_tag 'logo-white.png'
  %p
    © FURIMA

app/views/layouts/_footer_no_menu.html.haml
%footer.footer-no-menu
  %nav
    %ul
      = link_to "" do
        %li
          プライバシーポリシー
      = link_to "" do
        %li
          FURIMA利用規約
      = link_to "" do
        %li
          特定商取引に関する表記
  = image_tag 'logo.png', class: "logo"

app/views/layouts/_header.html.haml
%header.Header
  .headerInner
    .mainHeader
      %h1.icon
        = link_to root_path do
          = image_tag 'logo.png',class: "img1"
      .searchBox
        = form_with url: item_searches_path, class: "searchBox-form", method: :get, local: true  do |f|
          .field
            = f.search_field :name, name: "name_search", placeholder: "何かお探しですか?", class: "searchBox-form__text"
            = f.hidden_field :name, name: "q[name_search]"
            = f.label :search_btn, class: "search_btn-label" do
              = icon "fas", "search"
              = f.submit "", name: nil, class: "searchBox-form__loupe", id: "search_btn"
            
    .nav
      %nav.l-left
        %ul.listsLeft
          %li.listsLeft__item
            = link_to categories_path do
              = icon "fas", "list", class:"header-icon"
              カテゴリーから探す
          %li.listsLeft__item
            = icon "fas", "tags", class:"header-icon"
            ブランドから探す
      .l-right
        %ul.listsRight
          - if user_signed_in?
            %li.listsRight__item
              =link_to user_path(current_user) do
                #{current_user.nickname}さんのマイページ
          - else
            %li.listsRight__item.boder-main_color
              = link_to new_user_session_path, class:"sp-header-btn color-main" do
                ログイン
            %li.listsRight__item.back-main_color
              = link_to select_registration_path,class: "sp-header-btn back-main_color" do
                新規会員登録

app/views/layouts/_header_no_menu.html.haml
%header.header-no-menu
  = link_to root_path do
    = image_tag 'logo.png', class: "logo"
  -if @progress
    .progress-bar
      .progress
        .progress-title{class: "#{'doing' if @progress == 1}"}
          会員情報
        .progress-node
          .progress-node__circle{class: "#{'done' if @progress >= 1}"}
          .progress-node__line{class: "#{'done' if @progress >= 2}"}
      .progress
        .progress-title{class: "#{'doing' if @progress == 2}"}
          電話番号認証
        .progress-node
          .progress-node__circle{class: "#{'done' if @progress >= 2}"}
          .progress-node__line{class: "#{'done' if @progress >= 3}"}
      .progress
        .progress-title{class: "#{'doing' if @progress == 3}"}
          お届け先住所入力
        .progress-node
          .progress-node__circle{class: "#{'done' if @progress >= 3}"}
          .progress-node__line{class: "#{'done' if @progress >= 4}"}
      .progress
        .progress-title{class: "#{'doing' if @progress == 4}"}
          支払い方法
        .progress-node
          .progress-node__circle{class: "#{'done' if @progress >= 4}"}
          .progress-node__line{class: "#{'done' if @progress >= 5}"}
      .progress
        .progress-title{class: "#{'doing' if @progress == 5}"}
          完了
        .progress-node
          .progress-node__circle{class: "#{'done' if @progress >= 5}"}

app/views/layouts/_main_template.html.haml
= render 'layouts/flash'
= render 'layouts/header'
= yield

app/views/layouts/_purchaseBtn.html.haml
=link_to new_item_path do
  .purchaseBtn
    %span.purchaseBtn__text
      出品する
    = image_tag 'icon_camera.png',class: "purchaseBtn__icon"

app/views/layouts/_select_auth.html.haml
.block.horizontal-padding-25
  = link_to new_user_registration_path do
    .button.mail
      = icon "far", "envelope", class: "button__mail-icon"
      %span.button__text
        メールアドレス#{@auth_text}
  = link_to '#' do
    .button.facebook
      = icon "fab", "facebook-square", class: "button__facebook-icon"
      %span.button__text
        facebook#{@auth_text}
  = link_to user_google_oauth2_omniauth_authorize_path, method: :post do
    .button.google
      = image_tag "google_icon.png", class: "button__google-icon"
      %span.button__text
        Google#{@auth_text}

app/views/layouts/_sold_out.html.haml
-if item.deal == "sold_out"
  .sold-out
    .sold-out__text
      SOLD

app/views/layouts/_sub_template.html.haml
= render 'layouts/flash'
.horizontal-padding-25
  = render 'layouts/header_no_menu'
  = yield
  = render 'layouts/footer_no_menu'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF8", http: { equiv: "Contet-Type"}}/
    %title FurimaSample1
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    %script{src: "https://js.pay.jp/", type: "text/javascript"}
  %body
    - if controller.controller_name == "items" || controller.controller_name == "categories" || controller.controller_name == "item_searches"
      - case controller.action_name
      - when "index", "show"
        = render 'layouts/main_template'
        = render 'layouts/purchaseBtn'
        = render 'layouts/footer'
      - else 
        = render 'layouts/sub_template'
    - elsif controller.controller_name == "users" || controller.controller_name == "cards"
      - case controller.action_name
      - when "show", "new"
        = render 'layouts/main_template'
        = render 'layouts/footer'
      - else
        = render 'layouts/sub_template'
    - else
      = render 'layouts/sub_template'